language: java
jdk:
- openjdk8
script: mvn clean verify

deploy:
  provider: heroku
  api_key:
    secure: EPYf4T4U9WfJzHi4/CVp4gT9dogAtq6PmfnFz0j5Qem/FgKrpPP1FB4zgsXXv3PyH51WC0tRUCL/LnD8KNcCBmJoxdsCoufixr3JItbmeD45dyppSuwU2/bU/I+13/hc4eXpNHBE1tiq5PaPISSbcczmC3jE+iMttsn7lMkAMsLNM2P9MSzthpBveI4pXK3i7hj5wIEezqtcat632iQAfEnacnwJnHEqfyxtxISe4D9tfpBGElfSVw9P+f/yi7hsbb9+1K9gFpFtLCWsjAiDosQGA2AF/KhnT3lhkx/gJREX2HXzaAVx5MsIULWYh9/A8LIlghmj3sF23orEh2FiwNp4YTzqFTeyBLeK7mvpbMD2jCbKmDFSIgcMoGgiN9GbWcsRC1bmkpcwUab8wI2IMeEck8K+jR7+rUaP2ggq7OTFAe2im3sfg46HODZAoCj+mRFg1n3DtYL8ZDBppX6ivDl0y6rjF4QaqerLisTNNfer6UMFqG9PU0OoB5MidWwrfMcleN5UC5Qw0Ys4ykHJjDs9CnXQu7hAcEH4HvO/spW6zJz6uZhwxnAQi1hWtw3vPeIYXqtw8Nm/Tv9yDa4vAMbNiX7lqcorc9mCk6zcKCsXjvGThVz/IT9md+oracSjUt4vor8VBiEom3PXark9x5fbQ23DGw/bjGxpnqMbqv8=